CREATE SCHEMA IF NOT EXISTS ${schema_name};

CREATE TABLE IF NOT EXISTS ${schema_name}.dhm_25m (
  rid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  rast raster
)
WITH (
	OIDS=FALSE
);

-- 2592575.0000000000000000,1213750.0000000000000000 
-- 2644725.0000000000000000,1261300.0000000000000000
-- 2644737.5 - 2592562.5 = 52175 .. div 25 = 2087
-- 1261312.5 - 1213737.5 = 47575 .. div 25 = 1903


-- 2593262.5 - 2592562.5 = 700 .. div 25 = 28
-- 1229862.5 - 1227862.5 = 2000 .. div 25 = 80


INSERT INTO ${schema_name}.dhm_25m(rast)
VALUES
(
  --ST_Tile(
    ST_AddBand(
      -- Make empty raster
      ST_MakeEmptyRaster(
        2087, -- Raster width x (in pixels)
        1903, -- Raster width y (in pixels)
        2592562.5, -- Upper left X coordinate
        1261312.5, -- Upper left Y coordinate
        --28,
        --80,
        --2592562.5,
        --1229862.5,
        25, -- X Cell Resolution (in meters)  
        -25, -- Y Cell Resolution (in meters) 
        0, -- X skew
        0, -- Y skew
        2056 -- SRID
      ),
      -- We're making a single band raster, but you can add
      -- as many bands as you like by adding additional rows
      -- to the array.
      ARRAY [
        ROW (
          1,  -- Band index: sets this as the first band
          '32BF'::text,  -- Pixel Type (string rep of ST_BandPixelType types)
          NULL,  -- Initialized pixel value
          NULL  -- Nodata Value
        )
      ]::addbandarg[]
    )--, 
    --10, -- Number of cells per tile x
    --10, -- Number of cells per tile y
    --FALSE, -- Edge tiles can have different dimensions
    --NULL -- Nodata value
  --)
);

CREATE INDEX ${schema_name}_dhm25m_rast_gist_idx ON ${schema_name}.dhm_25m USING GIST (ST_ConvexHull(rast));

